# Automatically generated by configure - do not modify
TARGET_NAME=i386
target=i386-softmmu
CONFIG_SOFTMMU=y
QEMU=/home/kyle/emulator-work/xemu-clone/xemu-git/xemu-research/xemu/scripts/qemu-system-i386
CROSS_CC_GUEST_CFLAGS=-m32
